### ISSUE TITLE
VoteCrowdsale.sol not accepting payments within cap

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/exodus#1]
`revert` error when executing `NODE_ENV=test truffle test test/token/VoteCrowdsale.test.js `

```
Contract: VoteCrowdsale
    ✓ requires a non-null token (48ms)
    ✓ rejects a cap of zero (50ms)
    with crowdsale
      accepting payments
        1) "before each" hook for "should accept payments within cap"


  2 passing (522ms)
  1 failing

  1) Contract: VoteCrowdsale
       with crowdsale
         "before each" hook for "should accept payments within cap":
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by medied** [comment]
From `#beginners` channel of Zeppelin's Slack - https://vmexceptionwhileprocessingtransactionrevert.com/

**Comment by medied** [comment]
>https://vmexceptionwhileprocessingtransactionrevert.com/

Still haven't tried all suggestions from here, need to debug possibly including events as suggested [in  chat](https://openzeppelin.slack.com/archives/C4GP7FGM7/p1536887082000100) too

**Comment by medied** [comment]
Need to keep in mind Zeppelin's codebase is still in flux. Right now [package.json](https://github.com/DemocracyEarth/exodus/blob/master/package.json) does have next version and it's also why I was testing without proxy in [drafts](https://github.com/DemocracyEarth/exodus/blob/master/contracts/drafts/README.md). 

Read the [pre-release notes](https://github.com/OpenZeppelin/openzeppelin-solidity/releases/tag/v2.0.0-rc.1) of OpenZeppelin v2.0



<img width="470" alt="bf3bb642-8e34-4703-8549-444ac048d5d1" src="https://user-images.githubusercontent.com/4752599/45564497-9b5ea180-b81e-11e8-9f25-5fefb7ad9507.png">
