### ISSUE TITLE
SimpleCappedCrowdsale.sol not accepting payments within cap

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/exodus#2]
Error below when executing `truffle test test/drafts/SimpleCappedCrowdsale.test.js`

```
 Error: sender doesn't have enough funds to send tx. The upfront cost is: 42000000000006721975 and the sender's account only has: 15999999999999786184
```

**Comment by medied** [comment]
Get the same error when running `truffle test test/crowdsale/Crowdsale.test.js` directly from [openzeppelin-solidity source](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/test/crowdsale/Crowdsale.test.js)

```
Contract: Crowdsale
    ✓ requires a non-null token (49ms)
    with token
      ✓ requires a non-zero rate
      ✓ requires a non-null wallet (39ms)
      once deployed
        accepting payments
          bare payments
            1) should accept payments

    Events emitted during test:
    ---------------------------

    Transfer(from: <indexed>, to: <indexed>, value: 1e+22)
    Transfer(from: <indexed>, to: <indexed>, value: 1e+22)

    ---------------------------
            ✓ reverts on zero-valued payments
          buyTokens
            ✓ should accept payments (69ms)
            ✓ reverts on zero-valued payments
            ✓ requires a non-null beneficiary (58ms)
        high-level purchase
          ✓ should log purchase (59ms)
          ✓ should assign tokens to sender (66ms)
          ✓ should forward funds to wallet (58ms)
        low-level purchase
          ✓ should log purchase (50ms)
          2) should assign tokens to beneficiary

    Events emitted during test:
    ---------------------------

    Transfer(from: <indexed>, to: <indexed>, value: 1e+22)
    Transfer(from: <indexed>, to: <indexed>, value: 1e+22)

    ---------------------------
          3) should forward funds to wallet

    Events emitted during test:
    ---------------------------

    Transfer(from: <indexed>, to: <indexed>, value: 1e+22)
    Transfer(from: <indexed>, to: <indexed>, value: 1e+22)

    ---------------------------


  11 passing (3s)
  3 failing

  1) Contract: Crowdsale
       with token
         once deployed
           accepting payments
             bare payments
               should accept payments:
     Error: sender doesn't have enough funds to send tx. The upfront cost is: 42000000000006721975 and the sender's account only has: 17234693399981033622
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) Contract: Crowdsale
       with token
         once deployed
           low-level purchase
             should assign tokens to beneficiary:
     Error: sender doesn't have enough funds to send tx. The upfront cost is: 42000000000006721975 and the sender's account only has: 15999999999999786184
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  3) Contract: Crowdsale
       with token
         once deployed
           low-level purchase
             should forward funds to wallet:
     Error: sender doesn't have enough funds to send tx. The upfront cost is: 42000000000006721975 and the sender's account only has: 15999999999999786184
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by medied** [comment]
[The cost of your deployment is based on 5 things, with a 6th affecting the estimated cost of deployment
](https://ethereum.stackexchange.com/questions/35539/what-is-the-real-price-of-deploying-a-contract-on-the-mainnet)
[When sending ether be aware of the relative tradeoffs between the use of someAddress.send(), someAddress.transfer(), and someAddress.call.value()():
](https://ethereum.stackexchange.com/questions/38387/contract-address-transfer-method-gas-cost)

Tried changing/adjusting gas variables (`gas`, `gasPrice`) in both truffle config file and ganache setting but the error is still the same, the numbers never change, seems it's not recognizing anything. What else to try, [restart machine](https://github.com/trufflesuite/truffle/issues/1062#issuecomment-399763511)? And get coffee meanwhile I suppose... (yea that didn't work).
